# Change these first
owner: Compass-data # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:

  - name: Shopify
    url:  https://www.shopify.com/
  - name: Shopify Accounts
    url: https://accounts.shopify.com/
  - name: Aument.io
    url: https://aument.io/
  - name: Aument App
    url: https://platform.aument.io 


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statuspage

  logoUrl: 
  name: statuspage
  introTitle: ""
  introMessage: ""
  navbar:
    - title: -
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
